name: Generate README and SUMMARY

on:
  push:
    branches:
      - main

jobs:
  execute_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Set Timezone to Beijing
      run: |
        sudo timedatectl set-timezone Asia/Shanghai

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Execute Python Scripts
      run: |
        python gen_readme.py > README.md
        python gen_summary.py > SUMMARY.md

    - name: Commit and Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md SUMMARY.md
        git commit -m "Generate README and SUMMARY"
        git push origin main
