name: Generate README and SUMMARY

on:
  push:
    branches:
      - main

jobs:
  execute_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Execute Python Scripts
      run: |
        python gen_readme.py > README.md
        python gen_summary.py > SUMMARY.md

    - name: Commit and Push
      run: |
        git config --global user.email "zhangpeng.0304@aliyun.com"
        git config --global user.name "zhangpeng"
        git add README.md SUMMARY.md
        git commit -m "Generate README and SUMMARY"
        git push
        git push origin main:gitbook
